azure:
  activedirectory:
    b2c:
      tenant: cortexCapital
      client-id: 6e741d01-da33-4d48-b232-1d68994959d0
      client-secret: 3h^Y1[H\4hiy^0o.8DP5cAx/
      reply-url: http://localhost:8080/login/oauth2/code/azure # should be absolute url.
      logout-success-url: http://localhost:8080
      user-flows:
        sign-up-or-sign-in: B2C_1_test_user_flow
        profile-edit: ${your-profile-edit-user-flow}     # optional
        password-reset: ${your-password-reset-user-flow} # optional