azure:
  activedirectory:
    b2c:
      tenant: cortexCapital
      client-id: 6e741d01-da33-4d48-b232-1d68994959d0
      client-secret: 3h^Y1[H\4hiy^0o.8DP5cAx/
      reply-url: http://localhost:8080/home # should be absolute url. 
      # http://localhost:8080/login/oauth2/code/azure from the other tutorial 
      # https://docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory?view=azure-java-stable
      logout-success-url: http://localhost:8080/home
      user-flows:
        sign-up-or-sign-in: B2C_1_test_user_flow
        profile-edit: B2C_1_profile_editing     # optional
        password-reset: B2C_1_Password_Reset # optional